#pragma once

#undef DUK_USE_TARGET_INFO
#define DUK_USE_TARGET_INFO "musashi2"

#define DUK_USE_FASTINT

#define DUK_USE_DEBUGGER_SUPPORT
#define DUK_USE_DEBUGGER_FWD_LOGGING
#define DUK_USE_DEBUGGER_FWD_PRINTALERT
#define DUK_USE_DEBUGGER_PAUSE_UNCAUGHT
#define DUK_USE_DEBUGGER_INSPECT
#define DUK_USE_DEBUGGER_DUMPHEAP
#define DUK_USE_INTERRUPT_COUNTER
#define DUK_USE_DEBUGGER_THROW_NOTIFY

#define MUDUK_USE_DEBUG_GET_CLOSURES 1

//#define DUK_USE_DEBUG